version: "3.3"
services:
  spark-master:
    image: spark-master:latest
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       -  /bdb/conf:/opt/spark-conf
       -  /bdb/jars:/opt/spark-jars
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker:
    image: spark-worker:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=6G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=2G
    volumes:
       -  /bdb/conf:/opt/spark-conf
       -  /bdb/jars:/opt/spark-jars
